/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { PinkSale, PinkSaleInterface } from "../PinkSale";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "a",
        type: "address",
      },
    ],
    name: "contributionOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "a",
        type: "address",
      },
    ],
    name: "purchasedOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class PinkSale__factory {
  static readonly abi = _abi;
  static createInterface(): PinkSaleInterface {
    return new utils.Interface(_abi) as PinkSaleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PinkSale {
    return new Contract(address, _abi, signerOrProvider) as PinkSale;
  }
}
